//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliklinikOtomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLDOKTOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLDOKTOR()
        {
            this.TBLHASTA = new HashSet<TBLHASTA>();
        }
    
        public int Id { get; set; }
        public string KimlikNo { get; set; }
        public string AdiSoyadi { get; set; }
        public string TelefonNo { get; set; }
        public string Cinsiyeti { get; set; }
        public string MailAdresi { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLHASTA> TBLHASTA { get; set; }
    }
}
