//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliklinikOtomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLHASTA
    {
        public int Id { get; set; }
        public string AdiSoyadi { get; set; }
        public string KimlikNo { get; set; }
        public string TelefonNo { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public string Cinsiyeti { get; set; }
        public Nullable<System.DateTime> RandevuTarihi { get; set; }
        public string KayitTipi { get; set; }
        public Nullable<int> DoktorId { get; set; }
    
        public virtual TBLDOKTOR TBLDOKTOR { get; set; }
    }
}
